global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'account-service'
    static_configs:
      - targets: ['account-service:8081']

  - job_name: 'transaction-service'
    static_configs:
      - targets: ['transaction-service:8082']

  - job_name: 'loan-service'
    static_configs:
      - targets: ['loan-service:8083']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8084']

  - job_name: 'mock-payment-service'
    static_configs:
      - targets: ['mock-payment-service:8085']
