server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  security:
    user:
      name: disabled
      password: disabled

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring.cloud.gateway:
  default-filters:
    - RemoveRequestHeader=Cookie
    - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  routes:
    - id: account-service
      uri: http://account-service:8081
      predicates:
        - Path=/api/accounts/**,/api/auth/**
      filters:
        - StripPrefix=1
        - name: JwtAuth
    - id: transaction-service
      uri: http://transaction-service:8082
      predicates:
        - Path=/api/transactions/**
      filters:
        - StripPrefix=1
        - name: JwtAuth
    - id: loan-service
      uri: http://loan-service:8083
      predicates:
        - Path=/api/loans/**
      filters:
        - StripPrefix=1
        - name: JwtAuth
    - id: notification-service
      uri: http://notification-service:8084
      predicates:
        - Path=/api/notifications/**
      filters:
        - StripPrefix=1
        - name: JwtAuth
    - id: mock-payment-service
      uri: http://mock-payment-service:8085
      predicates:
        - Path=/api/payments/**
      filters:
        - StripPrefix=1
        - name: JwtAuth
